
import localFont from "next/font/local";
import "./globals.css";

const neue = localFont({
    src: "./fonts/NeueMontreal-Regular.otf",
    variable: "--font-neue",
    weight: "100 900",
});


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${neue.variable}  antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
