import localFont from "next/font/local";
import "./globals.css";

const neue = localFont({
    src: "./fonts/NeueMontreal-Regular.otf",
    variable: "--font-neue",
    weight: "100 900",
});

export const metadata = {
    title: "Retrak",
    description: "Generated by Uzair Dev",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/logo-icon.svg" sizes="any" />
            </head>
            <body className={`${neue.variable}  antialiased`}>{children}</body>
        </html>
    );
}
